In [1]:
import pandas as pd
import numpy as np

In [2]:
export_data_load = "LivestockMeat_Exports.csv"
import_data_load = "LivestockMeat_Imports.csv"

In [3]:
export_data = pd.read_csv(export_data_load)
import_data = pd.read_csv(import_data_load)

In [4]:
#cut unneeded columns
to_cut = ['SOURCE_ID','HS_CODE','GEOGRAPHY_CODE','ATTRIBUTE_DESC', 'TIMEPERIOD_ID']
#table_country_export = export_data
export_data.drop(to_cut, inplace=True, axis=1)
import_data.drop(to_cut, inplace=True, axis=1)

In [5]:
#sort data
sorted_imports = import_data.sort_values(['GEOGRAPHY_DESC','YEAR_ID'])
sorted_imports = sorted_imports[sorted_imports['YEAR_ID'].between(2006, 2016)]

sorted_exports = export_data.sort_values(['GEOGRAPHY_DESC','YEAR_ID'])
sorted_exports = sorted_exports[sorted_exports['YEAR_ID'].between(2006, 2016)]

In [6]:
sorted_exports.head()

,COMMODITY_DESC,GEOGRAPHY_DESC,UNIT_DESC,YEAR_ID,AMOUNT
19094,"Meat and edible offal, of the poultry of headi...",Afghanistan,KG,2006,9.862200e+05
19095,"Meat and edible offal, of the poultry of headi...",Afghanistan,KG,2006,9.810000e+04
19096,"Meat and edible offal, of the poultry of headi...",Afghanistan,KG,2006,5.490000e+04
19097,"Meat and edible offal, of the poultry of headi...",Afghanistan,KG,2006,7.537550e+05
19242,"Meat and edible offal, of the poultry of headi...",Afghanistan,CWE,2006,3.770924e+06

In [7]:
#convert unit of measure to metric tons
conversion_rate={'KG':.001, 'CWE':.04536,'DOZ':.00091}
sorted_exports['Metric Tons'] = pd.to_numeric(sorted_exports['AMOUNT']) * sorted_exports['UNIT_DESC'].map(conversion_rate).fillna(1)
sorted_exports.head()

,COMMODITY_DESC,GEOGRAPHY_DESC,UNIT_DESC,YEAR_ID,AMOUNT,Metric Tons
19094,"Meat and edible offal, of the poultry of headi...",Afghanistan,KG,2006,9.862200e+05,986.220000
19095,"Meat and edible offal, of the poultry of headi...",Afghanistan,KG,2006,9.810000e+04,98.100000
19096,"Meat and edible offal, of the poultry of headi...",Afghanistan,KG,2006,5.490000e+04,54.900000
19097,"Meat and edible offal, of the poultry of headi...",Afghanistan,KG,2006,7.537550e+05,753.755000
19242,"Meat and edible offal, of the poultry of headi...",Afghanistan,CWE,2006,3.770924e+06,171049.128969

In [8]:
#list commodities to clean
commodity=sorted_exports.COMMODITY_DESC.unique()
commodity

array(['Meat and edible offal, of the poultry of heading 0105, of chickens, cuts and off',
       'Shell egg', 'Pork',
       'Sausages and similar products, of meat, meat offal or blood; food preparations b',
       'Beef and veal', 'Broiler',
       'Other prepared or preserved meat, meat offal or blood, of poultry of heading 010',
       'Bird eggs not in shell, frsh, frzn, cooked by water etc.',
       'Homogenized preparations of meat, meat offal or blood (subheading note 1)',
       'Meat of bovine animals, frozen, boneless, processed',
       'Egg product', "Birds' eggs, in shell, fresh, preserved or cooked",
       'Egg',
       'Meat and edible offal, of the poultry of heading 0105, of chickens, not cut in p',
       'Hams, shoulders and cuts thereof, of swine, bone in, except processed, fresh or ',
       'Meat of bovine animals, salted, in brine, dried or smoked',
       'Turkey',
       'Meat of swine nesoi, boned and cooked and packed in airtight containers, not con',
       'Other prepared or preserved meat, meat offal or blood, of the poultry of heading',
       'Meat of swine, nesoi, processed, frozen',
       'Carcasses and half-carcasses of veal, frozen',
       'Meat of bovine animals, boneless, except processed, frozen',
       'Carcasses and half-carcasses of swine, frozen', 'Bacon',
       'Hams and cuts thereof, of swine, nesoi, prepared or preserved',
       'Meat or meat offal of bovine animals, nesoi, prepared or preserved',
       'Other chicken',
       'Hams and cuts thereof, of swine, boned and cooked and packed in airtight contain',
       'Chickens, nesoi, not cut in pieces, frozen',
       'Meat of bovine animals, cuts with bone in, except processed, frozen',
       'Turkeys, breasts or parts thereof, frozen',
       'Bird eggs not in shell, died, whether or not sweetened',
       '*Meat of swine, nesoi, salted, in brine, dried or smoked',
       'Meat of swine, nesoi, except processed, fresh or chilled',
       'Turkeys, not cut in pieces, frozen',
       'Turkeys, other cuts and offal, frozen',
       'Meat of swine, nesoi, processed, fresh or chilled',
       'Animal meat, nesoi, including preparations of blood of any animal, prepared or p',
       'Meat of bovine animals, fresh or chilled, other cuts with bone in, processed',
       'Mutton', 'Meat of sheep, cuts with bone in, nesoi, frozen',
       'Other egg albumin, except dried',
       'Meat of bovine animals, frozen, other cuts with bone in, processed',
       'Meat of sheep, boneless, frozen',
       'Hams, shoulders and cuts thereof, of swine, bone in, processed, frozen',
       'Meat of swine, nesoi, except processed, frozen',
       'Chickens, nesoi, not cut in pieces, fresh, chilled',
       'Meat of bovine animals, boneless, except processed, fresh or chilled',
       'Hams, shoulders and cuts thereof, of swine, bone in, processed, fresh or chilled',
       'Hams, shoulders and cuts thereof, of swine, bone in, salted, in brine, dried or ',
       'Hams, shoulders and cuts thereof, of swine, bone in, except processed, frozen',
       'Turkeys, offal, frozen',
       'Turkey, cuts and offal, fresh or chilled',
       'Turkeys, leg meat without bone, frozen',
       'Turkeys, wings or parts thereof, frozen',
       "Birds' eggs, in shell, for hatching",
       'Cattle, live, other than purebred breeding animals', 'Cattle',
       'Meat of bovine animals, cuts with bone in, except processed, fresh or chilled',
       'Turkey, legs with bone, frozen',
       'Meat of swine prepared or preserved, including mixtures, nesoi',
       'Turkeys, not cut in pieces, fresh or chilled',
       'Meat of swine nesoi, not containing cereals or vegetables, prepared or preserved',
       'Meat of sheep, boneless, fresh or chilled',
       'Prepared meals of turkey',
       'Carcasses and half-carcasses of bovine animals, nesoi, frozen',
       'Meat of bovine animals, fresh or chilled, boneless, processed',
       "Birds' of species gallus domesticus fresh eggs, not for hatching",
       'Bovine animals, live, purebred breeding, dairy, female',
       'Carcasses and half-carcasses of veal, fresh or chilled',
       'Carcasses and half-carcasses of bovine animals, nesoi, fresh or chilled',
       'Lamb', 'Carcasses and half-carcasses of lamb, fresh or chilled',
       "Birds', eggs, in shell, preserved or cooked",
       'Shoulders and cuts thereof, of swine, nesoi, prepared or preserved',
       'Meat of sheep, cuts with bone in, nesoi, fresh or chilled',
       'Carcasses and half-carcasses of sheep, frozen',
       'Carcasses and half-carcasses of lamb, frozen',
       'Carcasses and half-carcasses of swine, fresh or chilled',
       'Bellies (streaky) and cuts thereof, of swine, salted, in brine, dried or smoked',
       'Eggs of fowls of the species gallus domesticus (chicken), fertilized for incubat',
       'Goats, live', 'Goat',
       'Swine, live, nesoi, weighing less than 50 kg each', 'Hog',
       'Sheep', 'Sheep, live', 'Swine, live, purebred breeding animals',
       'Egg yolks, frsh, frzn, cooked by water, molded etc.',
       'Egg yolks, dried, whether or not sweetened', 'Egg albumin, dried',
       'Shoulders and cuts thereof, of swine, boned and cooked and packed in airtight co',
       'Swine, live, nesoi, weighing 50 kg or more each',
       'Bovine animals, live, purebred breeding, except dairy, female',
       'Bovine animals, live, nesoi',
       'Cattle, live, purebred breeding, except dairy, male',
       'Bovine animals, live, purebred breeding, dairy, male',
       'Bovine animals, live, purebred breeding, except dairy, male',
       'Cattle, live, purebred breeding, except dairy, female',
       'Carcasses and half-carcasses of sheep, fresh or chilled'],
      dtype=object)

In [13]:
#clean up of commodity types
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('turkey', case=False),'COMMODITY_DESC']='Turkey'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('chicken', case=False),'COMMODITY_DESC']='Chicken'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('bovine', case=False),'COMMODITY_DESC']='Beef'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('beef', case=False),'COMMODITY_DESC']='Beef'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('ham', case=False),'COMMODITY_DESC']='Pork'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('swine', case=False),'COMMODITY_DESC']='Pork'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('pork', case=False),'COMMODITY_DESC']='Pork'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('cattle', case=False),'COMMODITY_DESC']='Beef'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('broiler', case=False),'COMMODITY_DESC']='Chicken'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('sausage', case=False),'COMMODITY_DESC']='Pork'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('egg', case=False),'COMMODITY_DESC']='Chicken'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('veal', case=False),'COMMODITY_DESC']='Beef'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('goat', case=False),'COMMODITY_DESC']='Goat'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('sheep', case=False),'COMMODITY_DESC']='Sheep'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('mutton', case=False),'COMMODITY_DESC']='Sheep'
sorted_​exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('sheep', case=False),'COMMODITY_DESC']='Sheep'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('mutton', case=False),'COMMODITY_DESC']='Sheep'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('lamb', case=False),'COMMODITY_DESC']='Sheep'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('bacon', case=False),'COMMODITY_DESC']='Pork'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('poultry', case=False),'COMMODITY_DESC']='Chicken'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('hog', case=False),'COMMODITY_DESC']='Pork'
sorted_exports.loc[sorted_exports['COMMODITY_DESC'].str.contains('blood', case=False),'COMMODITY_DESC']='Pork'
sorted_exports

,COMMODITY_DESC,GEOGRAPHY_DESC,UNIT_DESC,YEAR_ID,AMOUNT,Metric Tons
19094,Chicken,Afghanistan,KG,2006,9.862200e+05,986.220000
19095,Chicken,Afghanistan,KG,2006,9.810000e+04,98.100000
19096,Chicken,Afghanistan,KG,2006,5.490000e+04,54.900000
19097,Chicken,Afghanistan,KG,2006,7.537550e+05,753.755000
19242,Chicken,Afghanistan,CWE,2006,3.770924e+06,171049.128969
...,...,...,...,...,...,...
975181,Chicken,Zimbabwe,KG,2012,2.444340e+05,244.434000
128517,Beef,Zimbabwe,CWE,2013,8.240015e+04,3737.670772
399936,Beef,Zimbabwe,KG,2013,2.630300e+04,26.303000
565085,Beef,Zimbabwe,KG,2013,2.630300e+04,26.303000
816466,Beef,Zimbabwe,CWE,2013,8.240015e+04,3737.670772

In [14]:
#check commodity list
commodity=sorted_exports.COMMODITY_DESC.unique()
commodity

array(['Chicken', 'Pork', 'Beef', 'Turkey', 'Sheep', 'Goat'], dtype=object)

In [15]:
#save file
sorted_exports.to_csv('exports_conversion.csv')

In [16]:
#add column with standardized units
sorted_imports['Metric Tons'] = pd.to_numeric(sorted_imports['AMOUNT']) * sorted_imports['UNIT_DESC'].map(conversion_rate).fillna(1)
sorted_imports.head()

,COMMODITY_DESC,GEOGRAPHY_DESC,UNIT_DESC,YEAR_ID,AMOUNT,Metric Tons
30128,"Meat of bovine animals, cured or pickled, no c...",Argentina,KG,2006,137101.0,137.101
30129,"Meat of bovine animals, cured or pickled, no c...",Argentina,KG,2006,87009.0,87.009
30150,"Corned beef, nesoi, no cereals or vegetables, ...",Argentina,KG,2006,9386.0,9.386
30151,"Corned beef, nesoi, no cereals or vegetables, ...",Argentina,KG,2006,19475.0,19.475
30152,"Corned beef, nesoi, no cereals or vegetables, ...",Argentina,KG,2006,122693.0,122.693

In [18]:
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('turkey', case=False),'COMMODITY_DESC']='Turkey'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('chicken', case=False),'COMMODITY_DESC']='Chicken'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('bovine', case=False),'COMMODITY_DESC']='Beef'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('beef', case=False),'COMMODITY_DESC']='Beef'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('ham', case=False),'COMMODITY_DESC']='Pork'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('swine', case=False),'COMMODITY_DESC']='Pork'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('pork', case=False),'COMMODITY_DESC']='Pork'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('cattle', case=False),'COMMODITY_DESC']='Beef'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('broiler', case=False),'COMMODITY_DESC']='Chicken'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('sausage', case=False),'COMMODITY_DESC']='Pork'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('egg', case=False),'COMMODITY_DESC']='Chicken'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('veal', case=False),'COMMODITY_DESC']='Beef'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('goat', case=False),'COMMODITY_DESC']='Goat'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('sheep', case=False),'COMMODITY_DESC']='Sheep'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('mutton', case=False),'COMMODITY_DESC']='Sheep'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('sheep', case=False),'COMMODITY_DESC']='Sheep'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('mutton', case=False),'COMMODITY_DESC']='Sheep'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('lamb', case=False),'COMMODITY_DESC']='Sheep'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('bacon', case=False),'COMMODITY_DESC']='Pork'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('poultry', case=False),'COMMODITY_DESC']='Chicken'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('hog', case=False),'COMMODITY_DESC']='Pork'
sorted_imports.loc[sorted_imports['COMMODITY_DESC'].str.contains('blood', case=False),'COMMODITY_DESC']='Pork'
sorted_imports

,COMMODITY_DESC,GEOGRAPHY_DESC,UNIT_DESC,YEAR_ID,AMOUNT,Metric Tons
30128,Beef,Argentina,KG,2006,137101.000000,137.101000
30129,Beef,Argentina,KG,2006,87009.000000,87.009000
30150,Beef,Argentina,KG,2006,9386.000000,9.386000
30151,Beef,Argentina,KG,2006,19475.000000,19.475000
30152,Beef,Argentina,KG,2006,122693.000000,122.693000
...,...,...,...,...,...,...
261330,Sheep,World,CWE,2016,497062.894608,22546.772899
261418,Sheep,World,CWE,2016,623109.952836,28264.267461
261419,Sheep,World,CWE,2016,411554.425716,18668.108750
261420,Sheep,World,CWE,2016,638127.837900,28945.478727
261421,Sheep,World,CWE,2016,838466.248284,38032.829022

In [19]:
#save file
sorted_imports.to_csv('imports_conversion.csv')